In [3]:
import numpy as np
arr=np.array([[4,5,6],[7,8,9]])
print(arr)

[[4 5 6]
 [7 8 9]]


In [26]:
arr.shape[1]

3L

In [5]:
arr[:,-1]

array([6, 9])

In [6]:
arr[:,-2]

array([5, 8])

In [7]:
arr[:,-1:]

array([[6],
       [9]])

In [13]:
arr[:,-2:]

array([[5, 6],
       [8, 9]])

In [8]:
arr[:,:-1]  

array([[4, 5],
       [7, 8]])

In [24]:
np.sum(arr[:,:-1],axis=1).reshape(-1,1)

array([[ 9],
       [15]])

In [30]:
arr1=np.sum(arr[:,:-1],axis=0)
print arr1

[11 13]


In [29]:
arr1.shape[0]

2L

In [10]:
arr[:1,:-2]

array([[4]])

In [11]:
arr[1:,:-1]

array([[7, 8]])

In [12]:
arr[0:1,1:2]

array([[5]])

In [14]:
arr[:,2]

array([6, 9])

In [16]:
for i in range(10,1,-1):
    print i

10
9
8
7
6
5
4
3
2
